version: '2.2'

services:
    backend:
      build:
        context : ./Back-End
        dockerfile : ./Dockerfile
      image : 'backendda2'
      ports :
        - 4000:4000
    frontent:
      build :
        context : ./front-end
        dockerfile: ./Dockerfile
      image : 'frontda2'
      ports :
        - 3000:3000
      links :
        - "backend:be"